<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Part;

class PartSeeder extends Seeder
{
    public function run(): void
    {
        $parts = [
            // -------- Furniture --------
            [
                'part_number' => 'FUR-1001',
                'serial_number' => 'SN-CHAIR-001',
                'name' => 'Office Chair',
                'facility_classification' => 'general',
                'facility_type' => 'officeFurniture',
                'facility_details' => 'Ergonomic chair with wheels',
                'location' => 'egypt',
                'department_id' => 1,
                'type' => 'furniture',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'new',
                'qr_code' => 'FUR1001-QR',
                'price' => 1200,
                'vat' => 14,
                'all_vat' => 1368,
                'checkup_schedule' => 'monthly',
                'last_checkup' => now()->subMonth(),
                'next_checkup' => now()->addMonth(),
            ],
            [
                'part_number' => 'FUR-1002',
                'serial_number' => null,
                'name' => 'Wooden Desk',
                'facility_classification' => 'directDedicated',
                'facility_type' => 'officeFurniture',
                'facility_details' => 'Large oak desk with drawers',
                'location' => 'egypt',
                'department_id' => 1,
                'type' => 'furniture',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'checked-out',
                'condition' => 'like-new',
                'qr_code' => 'FUR1002-QR',
                'price' => 2500,
                'vat' => 14,
                'all_vat' => 2850,
                'checkup_schedule' => 'bi-weekly',
                'last_checkup' => now()->subWeeks(2),
                'next_checkup' => now()->addWeeks(2),
            ],
            [
                'part_number' => 'FUR-1003',
                'serial_number' => null,
                'name' => 'Filing Cabinet',
                'facility_classification' => 'indirectDedicated',
                'facility_type' => 'officeFurniture',
                'facility_details' => 'Metal cabinet with 4 drawers',
                'location' => 'saudi',
                'department_id' => 2,
                'type' => 'furniture',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'needs-fix',
                'qr_code' => 'FUR1003-QR',
                'price' => 900,
                'vat' => 10,
                'all_vat' => 990,
                'checkup_schedule' => 'weekly',
                'last_checkup' => now()->subDays(6),
                'next_checkup' => now()->addDays(7),
            ],
            [
                'part_number' => 'FUR-1004',
                'serial_number' => 'SN-SOFA-001',
                'name' => 'Reception Sofa',
                'facility_classification' => 'general',
                'facility_type' => 'officeFurniture',
                'facility_details' => 'Leather sofa for lobby',
                'location' => 'egypt',
                'department_id' => 3,
                'type' => 'furniture',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'checked-out',
                'condition' => 'damaged',
                'qr_code' => 'FUR1004-QR',
                'price' => 4500,
                'vat' => 14,
                'all_vat' => 5130,
                'checkup_schedule' => 'monthly',
                'last_checkup' => now()->subMonths(2),
                'next_checkup' => now()->addMonths(1),
            ],
            [
                'part_number' => 'FUR-1005',
                'serial_number' => null,
                'name' => 'Conference Table',
                'facility_classification' => 'private',
                'facility_type' => 'officeFurniture',
                'facility_details' => '10-seat wooden conference table',
                'location' => 'saudi',
                'department_id' => 3,
                'type' => 'furniture',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'like-new',
                'qr_code' => 'FUR1005-QR',
                'price' => 6000,
                'vat' => 12,
                'all_vat' => 6720,
                'checkup_schedule' => 'bi-weekly',
                'last_checkup' => now()->subWeeks(1),
                'next_checkup' => now()->addWeeks(1),
            ],
            [
                'part_number' => 'FUR-1006',
                'serial_number' => 'SN-SHELF-001',
                'name' => 'Storage Shelf',
                'facility_classification' => 'general',
                'facility_type' => 'officeFurniture',
                'facility_details' => 'Steel rack for documents',
                'location' => 'egypt',
                'department_id' => 2,
                'type' => 'furniture',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'checked-out',
                'condition' => 'new',
                'qr_code' => 'FUR1006-QR',
                'price' => 1800,
                'vat' => 14,
                'all_vat' => 2052,
                'checkup_schedule' => 'almost-daily',
                'last_checkup' => now()->subDays(2),
                'next_checkup' => now()->addDays(5),
            ],

            // -------- Devices --------
            [
                'part_number' => 'DEV-2001',
                'serial_number' => 'SN-LAPTOP-001',
                'name' => 'Dell Laptop',
                'facility_classification' => 'private',
                'facility_type' => 'serviceDevices',
                'facility_details' => 'Dell XPS 15, i7, 16GB RAM',
                'location' => 'saudi',
                'department_id' => 1,
                'type' => 'device',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'needs-fix',
                'qr_code' => 'DEV2001-QR',
                'price' => 7000,
                'vat' => 15,
                'all_vat' => 8050,
                'checkup_schedule' => 'weekly',
                'last_checkup' => now()->subWeek(),
                'next_checkup' => now()->addWeek(),
            ],
            [
                'part_number' => 'DEV-2002',
                'serial_number' => null,
                'name' => 'Projector',
                'facility_classification' => 'indirectDedicated',
                'facility_type' => 'serviceDevices',
                'facility_details' => 'Epson projector for meeting room',
                'location' => 'saudi',
                'department_id' => 2,
                'type' => 'device',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'damaged',
                'qr_code' => 'DEV2002-QR',
                'price' => 3000,
                'vat' => 15,
                'all_vat' => 3450,
                'checkup_schedule' => 'almost-daily',
                'last_checkup' => now()->subDays(3),
                'next_checkup' => now()->addDays(2),
            ],
            [
                'part_number' => 'DEV-2003',
                'serial_number' => 'SN-PRINTER-001',
                'name' => 'HP Printer',
                'facility_classification' => 'general',
                'facility_type' => 'serviceDevices',
                'facility_details' => 'HP LaserJet, black & white',
                'location' => 'egypt',
                'department_id' => 1,
                'type' => 'device',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'checked-out',
                'condition' => 'like-new',
                'qr_code' => 'DEV2003-QR',
                'price' => 1500,
                'vat' => 10,
                'all_vat' => 1650,
                'checkup_schedule' => 'bi-weekly',
                'last_checkup' => now()->subWeeks(2),
                'next_checkup' => now()->addWeeks(2),
            ],
            [
                'part_number' => 'DEV-2004',
                'serial_number' => null,
                'name' => 'Security Camera',
                'facility_classification' => 'directDedicated',
                'facility_type' => 'safetyEquipment',
                'facility_details' => 'IP camera for entrance monitoring',
                'location' => 'saudi',
                'department_id' => 3,
                'type' => 'device',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'new',
                'qr_code' => 'DEV2004-QR',
                'price' => 2000,
                'vat' => 15,
                'all_vat' => 2300,
                'checkup_schedule' => 'weekly',
                'last_checkup' => now()->subDays(7),
                'next_checkup' => now()->addDays(7),
            ],
            [
                'part_number' => 'DEV-2005',
                'serial_number' => 'SN-SERVER-001',
                'name' => 'Rack Server',
                'facility_classification' => 'private',
                'facility_type' => 'serviceDevices',
                'facility_details' => 'Dell PowerEdge rack server',
                'location' => 'egypt',
                'department_id' => 2,
                'type' => 'device',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'checked-out',
                'condition' => 'damaged',
                'qr_code' => 'DEV2005-QR',
                'price' => 25000,
                'vat' => 14,
                'all_vat' => 28500,
                'checkup_schedule' => 'monthly',
                'last_checkup' => now()->subMonths(1),
                'next_checkup' => now()->addMonths(1),
            ],
            [
                'part_number' => 'DEV-2006',
                'serial_number' => null,
                'name' => 'Tablet Device',
                'facility_classification' => 'general',
                'facility_type' => 'serviceDevices',
                'facility_details' => 'Samsung Galaxy Tab A7',
                'location' => 'egypt',
                'department_id' => 3,
                'type' => 'device',
                'photo' => 'https://via.placeholder.com/150',
                'status' => 'available',
                'condition' => 'like-new',
                'qr_code' => 'DEV2006-QR',
                'price' => 1200,
                'vat' => 10,
                'all_vat' => 1320,
                'checkup_schedule' => 'weekly',
                'last_checkup' => now()->subWeek(),
                'next_checkup' => now()->addWeek(),
            ],
        ];

        foreach ($parts as $data) {
            Part::create($data);
        }
    }
}
